### ISSUE TITLE
Example for rules

### ISSUE THREAD

**Issue by popugang** [anvilabs/eslint-config#48]
how to override rules in .eslintrc.js. For example, i try like eslint `quotes: ["single"]` and like prettier `singleQuote: true`. But it doesnt work

**Comment by yenbekbay** [comment]
@Popugune Our [base config](https://github.com/anvilabs/eslint-config/tree/master/packages/eslint-config) extends [eslint-config-airbnb-prettier](https://github.com/prettier/eslint-config-prettier), which  disables the [`quotes` rule](https://github.com/prettier/eslint-config-prettier/blob/v2.9.0/index.js#L15). You don't need this rule as prettier takes care of all the formatting.

If you want prettier to enforce single quotes, just [enable the respective option](https://prettier.io/docs/en/options.html#quotes).

Hope this helps.
